// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function ConvertImage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ConvertImage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function Copy_To_Clipboard(arg1) {
  return window['go']['main']['App']['Copy_To_Clipboard'](arg1);
}

export function InitialConfigRead() {
  return window['go']['main']['App']['InitialConfigRead']();
}

export function MinimiseApp() {
  return window['go']['main']['App']['MinimiseApp']();
}

export function Open_Input_File_Dialog() {
  return window['go']['main']['App']['Open_Input_File_Dialog']();
}

export function Open_Output_Dir_Dialog() {
  return window['go']['main']['App']['Open_Output_Dir_Dialog']();
}

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function WriteExtraOptions(arg1, arg2) {
  return window['go']['main']['App']['WriteExtraOptions'](arg1, arg2);
}

export function WriteIndentingAmount(arg1) {
  return window['go']['main']['App']['WriteIndentingAmount'](arg1);
}

export function WriteOutputCodeOptions(arg1, arg2) {
  return window['go']['main']['App']['WriteOutputCodeOptions'](arg1, arg2);
}

export function WriteOutputFormats(arg1, arg2) {
  return window['go']['main']['App']['WriteOutputFormats'](arg1, arg2);
}

export function WriteOutputQualities(arg1, arg2) {
  return window['go']['main']['App']['WriteOutputQualities'](arg1, arg2);
}
